debug: true

metrics: true

spider:
  limit_rules:
    - domain: "*httpbin.*"
      limit: 10
      delay: 10s

    - domain: "*"
      limit: 10
      delay: 20s

targets:
  - name: "example.com"
    root: "https://example.com"
    render: true
    domain_only: true
    ref_filters:
      - ".next a[href]"
      - ".prev a[href]"

  - name: "news-website"
    root: "https://news-website.com"
    render: false
    domain_only: false
    rate_limit: 10
    ref_filters:
      - "a[href]"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  prefix: "spider"
